name: medicine_tracker
description: "An app to track medicine intake time."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  freezed: ^2.4.5
  shared_preferences: ^2.2.2
  bloc: ^8.1.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1
  path_provider: ^2.1.1
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  sqflite: ^2.3.0
  path: ^1.8.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  auto_route: ^7.8.4
  timezone: ^0.9.2
  flutter_timezone: ^1.0.8
  awesome_notifications_core: ^0.8.0 
  awesome_notifications: any
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2
  permission_handler: ^11.1.0

flutter:
  generate: true 
  uses-material-design: true
  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
